# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

# Basic Airflow cluster configuration for CeleryExecutor with Redis and PostgreSQL.
#
# WARNING: This configuration is for local development. Do not use it in a production deployment.
#
# This configuration supports basic configuration using environment variables or an .env file
# The following variables are supported:
#
# AIRFLOW_IMAGE_NAME           - Docker image name used to run Airflow.
#                                Default: apache/airflow:master-python3.8
# AIRFLOW_UID                  - User ID in Airflow containers
#                                Default: 50000
# AIRFLOW_GID                  - Group ID in Airflow containers
#                                Default: 50000
#
# Those configurations are useful mostly in case of standalone testing/running Airflow in test/try-out mode
#
# _AIRFLOW_WWW_USER_USERNAME   - Username for the administrator account (if requested).
#                                Default: airflow
# _AIRFLOW_WWW_USER_PASSWORD   - Password for the administrator account (if requested).
#                                Default: airflow
# _PIP_ADDITIONAL_REQUIREMENTS - Additional PIP requirements to add when starting all containers.
#                                Default: ''
#
# Feel free to modify this file to suit your needs.



x-airflow-common: &airflow-common
  image: ${AIRFLOW_IMAGE_NAME:-apache/airflow:2.8.1}
  environment: &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: CeleryExecutor
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow_db
    AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow_db
    AIRFLOW__CELERY__BROKER_URL: redis://:@redis:6379/0
    AIRFLOW__CORE__FERNET_KEY: ""
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
    AIRFLOW__CORE__LOAD_EXAMPLES: "true"
    AIRFLOW__API__AUTH_BACKEND: "airflow.api.auth.backend.basic_auth"
    AIRFLOW__SMTP__SMTP_HOST: "smtp.gmail.com"
    AIRFLOW__SMTP__SMTP_PORT: 587
    AIRFLOW__SMTP__SMTP_USER: "${AIRFLOW_SMTP_USER}"
    AIRFLOW__SMTP__SMTP_PASSWORD: "${AIRFLOW_SMTP_PASSWORD}"
    AIRFLOW__SMTP__SMTP_MAIL_FROM: "${AIRFLOW_SMTP_USER}"
    AIRFLOW__WEBSERVER__WORKER_TIMEOUT: 300
    API_USERNAME: "${API_USERNAME}"
    API_PASSWORD: "${API_PASSWORD}"
    _PIP_ADDITIONAL_REQUIREMENTS: ${_PIP_ADDITIONAL_REQUIREMENTS:- pymongo}
  volumes:
    - ./src/airflow/dags:/opt/airflow/dags
    - ./docker/airflow/logs:/opt/airflow/logs
    - ./docker/airflow/plugins:/opt/airflow/plugins
    - ./docker/airflow/init:/opt/airflow/init
  networks :
    - rakuten

  user: "${AIRFLOW_UID:-50000}:${AIRFLOW_GID:-50000}"
  depends_on:
    redis:
      condition: service_healthy

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    healthcheck:
      test:  ["CMD-SHELL", "echo 'db.runCommand({ ping: 1 })' | mongosh localhost/test --quiet"]
      interval: 10s
      timeout: 5s
      retries: 5  
    volumes:
      - mongo_data:/data/db
    networks:
      - rakuten

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres-init:/docker-entrypoint-initdb.d
    networks:
      - rakuten
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mlflow"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 20s

  mongo_initializer:
    build:
      context: .
      dockerfile: docker/mongo_initializer/Dockerfile
    container_name: mongo_initializer
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - ./src/data:/src
      - ./data:/data 
    networks:
      - rakuten
  
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 30s
      retries: 50
    restart: always
    networks:
      - rakuten

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'airflow jobs check --job-type SchedulerJob --hostname "$${HOSTNAME}"',
        ]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always

  airflow-worker:
    <<: *airflow-common
    command: celery worker
    healthcheck:
      test:
        - "CMD-SHELL"
        - 'celery --app airflow.executors.celery_executor.app inspect ping -d "celery@$${HOSTNAME}"'
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always

  airflow-init:
    <<: *airflow-common
    command: bash -c "airflow db upgrade && airflow users create --username airflow --password airflow --firstname Airflow --lastname Admin --role Admin --email airflow@example.com"
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_UPGRADE: "true"
      _AIRFLOW_WWW_USER_CREATE: "true"
      _AIRFLOW_WWW_USER_USERNAME: "${_AIRFLOW_WWW_USER_USERNAME}"
      _AIRFLOW_WWW_USER_PASSWORD: "${_AIRFLOW_WWW_USER_PASSWORD}"
  
  airflow-variable-init:
    <<: *airflow-common
    container_name: airflow-variable-init
    environment:
      <<: *airflow-common-env
    command: >
      bash -c "
      echo 'Attente du webserver...';
      until curl --fail http://airflow-webserver:8080/health; do sleep 20; done;
      echo 'Webserver opérationnel, initialisation des variables Airflow...';
      python /opt/airflow/init/init_variables.py
      "
    # depends_on:
    #   airflow-webserver:
    #     condition: service_healthy
    #   api:
    #     condition: service_healthy
    # restart: always


  flower:
    <<: *airflow-common
    command: celery flower
    ports:
      - 5555:5555
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5555/"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always

  mlflow:
    build:
      context: .
      dockerfile: docker/mlflow/Dockerfile
    container_name: mlflow
    command: [
      #"/wait-for-it.sh", "postgres", "5432", "--",
      "mlflow", "server",
      "--backend-store-uri=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}",
      "--default-artifact-root=mlflow-artifacts:/",
      "--artifacts-destination=/mlflow/mlruns",  
      "--host", "0.0.0.0",
      "--port", "5000",
      "--serve-artifacts",
      "--allowed-hosts", "localhost:*,127.0.0.1:*,mlflow:*,${IP_Tailscale:-100.126.74.73}:*"]
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlflow/mlruns
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - rakuten
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    restart: on-failure
    
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    container_name: api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./data/raw_data_test/images_test:/app/data/raw_data_test/images_test
      - ./.git:/app/.git
      - ./mlruns:/mlflow/mlruns
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - MLFLOW_ARTIFACT_ROOT=/mlflow/mlruns
      - PYTHONUNBUFFERED=1
      - SECRET_KEY="${SECRET_KEY}"
      - AIRFLOW_API_USER="${_AIRFLOW_WWW_USER_USERNAME}"
      - AIRFLOW_API_PASSWORD="${_AIRFLOW_WWW_USER_PASSWORD}"
      - MONGO_URI="${MONGO_URI}"
    depends_on:
      mongodb:
        condition: service_healthy
      mlflow:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - rakuten
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
#      - '--storage.tsdb.retention.time=1d'
    depends_on:
      - api
    networks:
      - rakuten

  grafana:
    image: grafana/grafana
    container_name: grafana_template_accidents
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - api
    networks:
      - rakuten

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8085:8080"  
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    command:
      - "--port=8085"
    depends_on:
      - api
    networks:
      - rakuten

volumes:
  postgres_data:  {}
  mongo_data:
    external: true
    name: mar25_cmlops_rakuten_mongo_data
  prometheus_data: {}
  grafana_data: {}

networks:
  rakuten:
